### ISSUE TITLE
Web -> Chat view: enable autoscrolling

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/elixirconf_chat#21]
Doc: https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.JS.html

**Comment by ryanwinchester** [comment]
I don't see autoscrolling docs in the link

**Comment by ryanwinchester** [comment]
```css
#scroller * {
  overflow-anchor: none;
}

#scroll-anchor {
  overflow-anchor: auto;
  height: 1px;
}
```

add `scroller` ID to the scrollable part of the chat and a new div at the bottom (yet inside) that container with `scroll-anchor` ID, that will keep the chat scrolled down.
